#!/bin/bash
# Report changes of external IP to email addresses
# Requires proper configuration of mailutils and postfix.
# These emails love being detected as spam; try a filter.
#
# Add these lines to your crontab to run this every 15 minutes:
#   SHELL=/bin/bash
#   */15 * * * * ~/bin/extip

ip_service="http://ipecho.net/plain"
file_path="${HOME}/external_ip.txt"
emails="email@example.org,email2@example.org"

hostname=$(cat /etc/hostname)
lastip=$(cat $file_path 2> /dev/null || echo "404")
currip=$(curl -s $ip_service)

if [[ $currip =~ ^[0-9.]+ ]] && [[ $lastip != $currip ]]
then
    echo $currip > $file_path
    mail -s "External IP change for $hostname" $emails < $file_path
fi
