#!/bin/bash
# Wee scriptie for reporting changes to external IP
# Requires proper configuration of mailutils

ip_service="http://ipecho.net/plain"
file_path="/home/steve/code/me/complex_solutions/external_ip.txt"
emails="steve@eardley.xyz"

hostname=$(cat /etc/hostname)
lastip=$(cat $file_path 2> /dev/null || echo "404")
currip=$(curl -s $ip_service)

if [ $lastip != $currip ]
then
    echo $currip > $file_path
    mail -s "External IP change for $hostname" $emails < $file_path
fi
