#!/bin/bash
# Wee scriptie for reporting changes to external IP
# Requires proper configuration of mailutils
# These emails love being detected as spam. Try a filter.

ip_service="http://ipecho.net/plain"
file_path="~/external_ip.txt"
emails="email@example.org,email2@example.org"

hostname=$(cat /etc/hostname)
lastip=$(cat $file_path 2> /dev/null || echo "404")
currip=$(curl -s $ip_service)

if [[ $currip =~ ^[0-9.]+ ]] && [[ $lastip != $currip ]]
then
    echo $currip > $file_path
    mail -s "External IP change for $hostname" $emails < $file_path
fi
